// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paste.Shared;

namespace Paste.Shared.Migrations
{
    [DbContext(typeof(PasteDbContext))]
    [Migration("20190116235600_AddDateAndUsageStats")]
    partial class AddDateAndUsageStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("Paste.Shared.Upload", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTimeOffset>("LastViewed");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.ToTable("Uploads");
                });
#pragma warning restore 612, 618
        }
    }
}
